### DISCUSSION TITLE
TOC best practices

### DISCUSSION THREAD

**Discussion by Mpdreamz** [elastic/docs-builder#388] [Discussion]
Our current post-migration script puts everything in file blocks with children:

```yaml
 - file: observability/get-started.md
        children:
          - file: observability/get-started/what-is-elastic-observability.md
          - file: observability/get-started/create-an-observability-project.md
          - file: observability/get-started/quickstart-monitor-hosts-with-elastic-agent.md
          - file: observability/get-started/quickstart-monitor-kubernetes-cluster-with-elastic-agent.md
          - file: observability/get-started/quickstart-monitor-hosts-with-opentelemetry.md
          - file: observability/get-started/quickstart-unified-kubernetes-observability-with-elastic-distributions-of-opentelemetry-edot.md
          - file: observability/get-started/quickstart-collect-data-with-aws-firehose.md
          - file: observability/get-started/add-data-from-splunk.md
          - file: observability/get-started/get-started-with-dashboards.md
```

I think it be better if we prefer folder directives in the toc.yml. 

```yaml
 - folder: observability/get-started
        children:
          - file: index.md
          - file: what-is-elastic-observability.md
          - file: create-an-observability-project.md
          - file: quickstart-monitor-hosts-with-elastic-agent.md
          - file: quickstart-monitor-kubernetes-cluster-with-elastic-agent.md
          - file: quickstart-monitor-hosts-with-opentelemetry.md
          - file: quickstart-unified-kubernetes-observability-with-elastic-distributions-of-opentelemetry-edot.md
          - file: quickstart-collect-data-with-aws-firehose.md
          - file: add-data-from-splunk.md
          - file: get-started-with-dashboards.md
```

This will make it a lot easier to manually rename/move folders. It will also greatly help us in engineering to create refactor tools later down the line.

There are also some folders that contain a flat list of files but that get projected into complex navigation structures:

See: https://github.com/elastic/asciidocalypse/tree/add-docs-content/docs/docs-content/docs/solutions/observability/apps

and its TOC:

https://github.com/elastic/asciidocalypse/blob/add-docs-content/docs/docs-content/docs/solutions/toc.yml#L17C7-L83

I personally find these very hard to navigate and would prefer more deeply nested folders grouping things logically in folders to match their logical grouping in the TOC. 

Instead of creating these groupings using file names folders work better:

- We can always flatten files in the output including folder names if we decide to limit folder depth.
- Renames are easier just rename the folder, no need to guess if a source file name pattern is intended or not.
