### ISSUE TITLE
[Feature Request]: Tags

### ISSUE THREAD

**Issue by reakaleek** [elastic/docs-builder#1200]
## Context

The legacy asciidob build supported tags.
In the [conf.yaml](https://github.com/elastic/docs/blob/master/conf.yaml#L185) you can see these tags applied at a book level.

These tags were also used to enhance the search experience, making it possible to filter by tags.

## Goal

Add a tags feature that can be used by the search feature for filtering.

## Requirements

- The user should be able to set one or more tags for a page.
- The user should be able to set a default tag for reference content.
  E.g. the logstash reference should have the "Logstash" tag by default
- The user should be able to append tags on a page, in addition to the default tag.
  Hence, if a default tag exists and the user adds tags to a page, it should contain both the default tag and the additional tags.

## Proposed implementation

1. Add a `tags` frontmatter option, these tags should then be added to HTML meta tags so that the web team can crawl and parse them.
2. Write a script to parse tags from [conf.yaml](https://github.com/elastic/docs/blob/master/conf.yaml#L185) and add it to frontmatter based on the `prefix` attribute in conf.yaml and `mapped_pages` frontmatter in elastic/docs-content. This means a page might have multiple tags.
3. Do a release so we can already utilize the tags for search.
4. Add a "default" tag feature for reference content. (Can we add it somehow to assembler.yml or navigation.yml?

## Open Questions

- What format should the meta tags be so that the webteam can parse them
- Can we add additional metadata for the search? E.g. content type, license, or version?
- What's the best way to add default tags for reference content? docset.yml, toc.yml, assembler.yml or navigation.yml?

## References

- https://search.elastic.co/?q=test&location%5B0%5D=Documentation
- https://github.com/elastic/docs/blob/master/conf.yaml#L185
- https://github.com/elastic/docs-content/blob/441bb97aad23441f057a8529984b252f6405b18c/deploy-manage/tools/snapshot-and-restore/ec-gcs-snapshotting.md?plain=1#L4

## Stakeholders

@elastic/docs-engineering, @KOTungseth, @colleenmcginnis, @elastic/webteam

**Comment by acsnyder** [comment]
There are a few meta tags the search crawler relies on for extracting data from pages.  The following meta tags have dummy data to illustrate what kind of data is needed.

````
<meta class="elastic" name="product_version" content="8.17"/>
<meta class="elastic" name="product_name" content="Elasticsearch"/>
<meta class="elastic" name="website_area" content="documentation"/>
<meta name="DC.subject" content="Elasticsearch"/>
````

The `DC.subject` meta tag may be duplicative of `product_name`, we can adjust the crawler if necessary.  I created [a ticket](https://github.com/elastic/docsmobile/issues/783) last year but it might've been added to a deprecated repository.

**Comment by acsnyder** [comment]
@reakaleek We could have multiple values separated by some kind of delimiter.  We'd have to update the crawler script for that.  Can you give an example of a page used for multiple products?

**Comment by KOTungseth** [comment]
> [@KOTungseth](https://github.com/KOTungseth), can you please help me find an example page?

Sure can!

- [Cloud Native Vulnerability Management Dashboard](https://www.elastic.co/docs/solutions/security/cloud/cloud-native-vulnerability-management) ([source file](https://github.com/elastic/docs-content/blob/main/solutions/security/dashboards/cloud-native-vulnerability-management-dashboard.md))
- [Deploy](https://github.com/elastic/docs-content/edit/main/deploy-manage/deploy.md) ([source file](https://github.com/elastic/docs-content/edit/main/deploy-manage/deploy.md))
- [Elastic Cloud on Kubernetes release notes](https://www.elastic.co/docs/release-notes/cloud-on-k8s) ([source file](https://github.com/elastic/cloud-on-k8s/edit/main/docs/release-notes/index.md))

**Comment by acsnyder** [comment]
Thanks @KOTungseth!  The second item (Deploy) is the same link as the source file.

Looking at your `mapped_pages` frontmatter, it looks like we may need to rethink how we crawl docs pages.  I'll comment later when I have some time to check locally.

**Comment by bmorelli25** [comment]
Another requirement:
* Use CI to enforce only product tags listed in column C can be added as frontmatter: https://docs.google.com/spreadsheets/d/1AVZMAOD0-RUXyRH0l9sIg5EG_AXqFCAAKQuj533aHzI/edit?gid=0#gid=0

**Comment by reakaleek** [comment]
@colleenmcginnis provided a list product names and their kebab-case mapping value.

<details>
<summary>mapping</summary>

```yaml
# I wasn't sure where to put this...
# We can delete it from here if we want to move it to docs-builder.
apm: 'APM'
apm-dotnet-agent: 'APM .NET Agent'
apm-android-agent: 'APM Android Agent'
apm-attacher: 'APM Attacher'
apm-aws-lambda-extension: 'APM AWS Lambda extension'
apm-go-agent: 'APM Go Agent'
apm-ios-agent: 'APM iOS Agent'
apm-java-agent: 'APM Java Agent'
apm-node-agent: 'APM Node.js Agent'
apm-php-agent: 'APM PHP Agent'
apm-python-agent: 'APM Python Agent'
apm-ruby-agent: 'APM Ruby Agent'
apm-rum-agent: 'APM RUM Agent'
beats-logging-plugin: 'Beats Logging plugin'
cloud-control-ecctl: 'Cloud Control ECCTL'
cloud-enterprise: 'Cloud Enterprise'
cloud-hosted: 'Cloud Hosted'
cloud-kubernetes: 'Cloud Kubernetes'
cloud-native-ingest: 'Cloud Native Ingest'
cloud-serverless: 'Cloud Serverless'
cloud-terraform: 'Cloud Terraform'
ecs-logging: 'ECS Logging'
ecs-logging-dotnet: 'ECS Logging .NET'
ecs-logging-go-logrus: 'ECS Logging Go Logrus'
ecs-logging-go-zap: 'ECS Logging Go Zap'
ecs-logging-go-zerolog: 'ECS Logging Go Zerolog'
ecs-logging-java: 'ECS Logging Java'
ecs-logging-node: 'ECS Logging Node.js'
ecs-logging-php: 'ECS Logging PHP'
ecs-logging-python: 'ECS Logging Python'
ecs-logging-ruby: 'ECS Logging Ruby'
elastic-agent: 'Elastic Agent'
ecs: 'Elastic Common Schema (ECS)'
elastic-products-platform: 'Elastic Products platform'
elastic-stack: 'Elastic Stack'
elasticsearch: 'Elasticsearch'
elasticsearch-dotnet-client: 'Elasticsearch .NET Client'
elasticsearch-apache-hadoop: 'Elasticsearch Apache Hadoop'
elasticsearch-cloud-hosted-heroku: 'Elasticsearch Cloud Hosted Heroku'
elasticsearch-community-clients: 'Elasticsearch community clients'
elasticsearch-curator: 'Elasticsearch Curator'
elasticsearch-eland-python-client: 'Elasticsearch Eland Python Client'
elasticsearch-go-client: 'Elasticsearch Go Client'
elasticsearch-groovy-client: 'Elasticsearch Groovy Client'
elasticsearch-java-client: 'Elasticsearch Java Client'
elasticsearch-java-script-client: 'Elasticsearch JavaScript Client'
elasticsearch-painless-scripting-language: 'Elasticsearch Painless scripting language'
elasticsearch-perl-client: 'Elasticsearch Perl Client'
elasticsearch-php-client: 'Elasticsearch PHP Client'
elasticsearch-plugins: 'Elasticsearch plugins'
elasticsearch-python-client: 'Elasticsearch Python Client'
elasticsearch-resiliency-status: 'Elasticsearch Resiliency Status'
elasticsearch-ruby-client: 'Elasticsearch Ruby Client'
elasticsearch-rust-client: 'Elasticsearch Rust Client'
fleet: 'Fleet'
ingest: 'Ingest'
integrations: 'Integrations'
kibana: 'Kibana'
logstash: 'Logstash'
machine-learning: 'Machine Learning'
observability: 'Observability'
reference-architectures: 'Reference Architectures'
search-ui: 'Search UI'
security: 'Security'
```

</details>

This list is incomplete and lacks products for some reference content.
But it's a complete list for docs-content.
