### ISSUE TITLE
[Feature Request]: Validate that first index.md has no children in toc.yml

### ISSUE THREAD

**Issue by theletterf** [elastic/docs-builder#1233]
### Prerequisites

- [x] I have searched existing issues to ensure this feature hasn't already been requested
- [x] I have tested using the latest version of docs-builder

### What problem are you trying to solve?

When adding children to `index.md` in a `toc.yml` file, the first navigation entry gets duplicated. 

Sample snippet:

```yaml
project: 'APM Java agent reference'
toc:
  - file: index.md
     children:
       - file: setup-javaagent.md
       - file: setup-attach-cli.md
    ...
```

Example result is a duplicated, nested "APM Java agent reference" entry.

### Proposed Solution

We could validate that the first index.md file doesn't have children.

### How important is this feature to you?

Nice to have
