### ISSUE TITLE
[Enhancement] Version dropdown

### ISSUE THREAD

**Issue by KOTungseth** [elastic/docs-builder#1327]
## Description
Currently, the version dropdown only appears on individual docs pages and only includes the current (such as Stack 9.0) and most recent previous version (such as Stack 8.18). Internal and external feedback has made it clear that users need easier access to more historical documentation versions—including legacy versions—to reduce friction and improve navigation.

## Goals

- Make the version dropdown persistently available in the docs-dedicated navigation bar (not just on individual docs pages).
- Expand the dropdown options to include:
   - Current version (9.0+)
   - All 8.x minor versions (8.0 through 8.18) as a context menu group
   - 7.17 (final 7.x release)
   - A link to an "All versions" page for access to 7.16 and earlier
- Ensure that selecting a version updates the current context (does not open a new tab).
- Create and maintain a new "All versions" index page in the elastic/docs-content repo.

## Scope
[Designs](https://www.figma.com/design/3FY9syuxOqUJCMcH9Elc1M/New-docs-site--design-fixes-April-2025-Design?node-id=1-18621&p=f&t=KAOkWwu2TZFPUm3w-0)

### Part 1: Landing page dropdown behavior
- Dropdown placement: Add the version dropdown next to "Docs" in the persistent top navigation.
- Version-specific behavior: When users select a version (7.17–8.18) on the landing page, they should be navigated to a version-specific AsciiDoc landing page that only lists content available for that version.
- New pages needed: Create AsciiDoc landing pages for each 8.x version and 7.17.

### Part 2: Docs page dropdown behavior
- Behavior: Selecting a version (7.17–8.18) on a docs page should navigate to the mapped AsciiDoc page for that version.
- Mappings: Update page mapping logic based on [8.x and 7.17 mappings](https://docs.google.com/spreadsheets/d/1fHb68cwAKk_V86VAiUVzciG-jCghrZ8WRiZ9daLyCOM/edit?gid=330022358#gid=330022358)
- Fallback: When a selected version doesn’t include the mapped page, display a “bummer” message, following the existing pattern for unavailable AsciiDoc pages.

## Out of Scope
Adding older (pre-7.17) versions directly to the dropdown. These will be accessed via the "All versions" link.

## Dependencies
 - Create version-specific AsciiDoc landing pages for 7.17–8.18
 - Update UI for persistent dropdown in navigation bar
 - Update dropdown component to include new structure and behaviors
 - Update mapping logic for docs page version switching
 - Add fallback messaging for missing pages
 - Create "All versions" index page (writers)

**Comment by KOTungseth** [comment]
```
What is the desired behaviour on a release notes page?

- Should it show the version of the product?

- Should it show the stack version?

```
Release notes are now consolidated on a single page and organized by major version. 

For all Stack versioned products, Elastic Cloud Hosted, and Elastic Cloud Serverless, `current` = 9.0+
This includes all pages under:
Elasticsearch
Kibana
Fleet and Elastic Agent
Logstash
Beats
Elastic Cloud Serverless
Elastic Coud Hosted
Elastic Security
ECS
 
For Elastic Cloud Enterprise, `current` = 4.0+

For Elastic Cloud on Kubernetes, `current` = 3.0+

For Elastic Observability and Elastic APM, current = 9.0+, however it gets spicy for Agents. If wee need to pull these up a level, we should. 

APM Agents:
Android, `current` = 1.0.0 (I know this doesn't make sense. I'd like @theletterf to chime in here)
.NET, `current` = 1.0+
Go, `current` = 2.0+
iOS, `current` = 1.0
Java, `current`= 1.0+
Node.js, `current` = 4.0+
PHP, `current` = 1.0+
Python, `current` = 6.0+
Ruby, `current` = 4.0+
ARM, `current` = 5.0+
Lambda, `current` = 1.0+

**Comment by KOTungseth** [comment]
`How does the dropdown look like for other projects (non stack-versioned) e.g. apm agent java (should it still show the “all versions” button?`

For docs that do not have "all versions" or any version that exists in /guide, we should show the [elastic.co](http://elastic.co/) bummer message.

![Image](https://github.com/user-attachments/assets/2999224b-f24f-4633-8b1a-d8d4543c2812)

**Comment by theletterf** [comment]
@KOTungseth It's indeed spicy for agents. Those apply to APM Agents. Android and iOS agents are indeed at 1.0.0 and 1.2.1, even though they've been rebranded as EDOT (not yet reflected in docs).

For EDOT, we keep track of the versions here, as subs: https://github.com/elastic/opentelemetry/blob/main/docs/docset.yml#L30-L38

**Comment by reakaleek** [comment]
<details>
<summary>Draft versions config</summary>

```yaml
versions:
  stack:
    # This is the default versioning scheme, used for most of the docs.
    # It uses the stack version as the current version.
    base: '9.0'
    current: '9.0.1' # https://artifacts.elastic.co/releases/stack.json
    legacy_versions: [ '8.18', '8.17', '8.16', '8.15', '8.14', '8.13', '8.12', '8.11', '8.10', '8.9', '8.8', '8.7', '8.6', '8.5', '8.4', '8.3', '8.2', '8.1', '8.0', '7.17' ]
  apm_agent_android:
    current: '1.0.0' # https://github.com/elastic/apm-agent-android/releases
    legacy_versions: [ '0.x' ]
  apm_agent_dotnet:
    current: '1.32.0' # https://github.com/elastic/apm-agent-dotnet/releases
    legacy_versions: [ '1.8' ]
  apm_agent_go:
    current: '2.7.1' # https://github.com/elastic/apm-agent-go/releases
    legacy_versions: [ '1.x', '0.5' ]
  apm_agent_java:
    current: '1.54.0' # https://github.com/elastic/apm-agent-java/releases
    legacy_versions: [ '0.7', '0.6' ]
  apm_agent_nodejs:
    current: '4.13.0' # https://github.com/elastic/apm-agent-nodejs/releases
    legacy_versions: [ '3.x', '2.x', '1.x' ]
  apm_agent_php:
    current: '1.15.0' # https://github.com/elastic/apm-agent-php/releases
    legacy_versions: []
  apm_agent_python:
    current: '6.23.0' # https://github.com/elastic/apm-agent-python/releases
    legacy_versions: [ '5.x', '4.x', '3.x', '2.x', '1.x' ]
  apm_agent_ruby:
    current: '4.7.3' # https://github.com/elastic/apm-agent-ruby/releases
    legacy_versions: [ '3.x', '2.x', '1.x' ]
  apm_agent_rum_js:
    current: '5.17.0' # https://github.com/elastic/apm-agent-rum-js/releases
    legacy_versions: [ '4.x', '3.x', '2.x', '1.x', '0.x' ]
  apm_agent_ios:
    current: '1.2.1' # https://github.com/elastic/apm-agent-ios/releases
    legacy_versions: [ '0.x' ]
  apm_k8s_attacher:
    current: '1.1.3' # https://github.com/elastic/apm-k8s-attacher/releases
    legacy_versions: []
  apm_aws_lambda:
    current: '1.5.8' # https://github.com/elastic/apm-aws-lambda/releases
    legacy_versions: []
  cloud_enterprise:
    path_prefix: en/cloud-enterprise
    current: '4.1.0' # https://github.com/elastic/cloud/blob/master/version
    legacy_versions: [ '3.8', '3.7', '3.6', '3.5', '3.4', '3.3', '3.2', '3.1', '3.0', '2.7', '2.6', '2.5', '2.4', '2.3', '2.2', '2.1', '2.0', '1.1', '1.0' ]
  cloud_heroku:
    current: 'current'
    legacy_versions: []
  cloud_on_k8s:
    current: '3.0.0' # https://github.com/elastic/cloud-on-k8s/releases
    legacy_versions: [ '2.16', '2.15', '2.14', '2.13', '2.12', '2.11', '2.10', '2.9', '2.8', '2.7', '2.6', '2.5', '2.4', '2.3', '2.2', '2.1', '2.0', '1.9', '1.8', '1.7', '1.6', '1.5', '1.4', '1.3', '1.2', '1.1', '1.0', '1.0-beta', '0.9', '0.8' ]
  cloud:
    current: 'current'
    legacy_versions: []
  ecctl:
    current: '1.14.3' # https://github.com/elastic/ecctl/releases
    legacy_versions: [ '1.13', '1.12', '1.11', '1.10', '1.9', '1.8', '1.7', '1.6', '1.5', '1.4', '1.3', '1.2', '1.1', '1.0' ]
  ecs_logging:
    current: 'current'
    legacy_versions: []
  ecs_logging_dotnet:
    current: '8.18.1' # https://github.com/elastic/ecs-dotnet/releases
    legacy_versions: []
  ecs_logging_go_logrus:
    current: '1.0.0' # https://github.com/elastic/ecs-logging-go-logrus/releases
    legacy_versions: []
  ecs_logging_go_zap:
    current: '1.0.3' # https://github.com/elastic/ecs-logging-go-zap/releases
    legacy_versions: []
  ecs_logging_go_zerolog:
    current: '0.2.0' # https://github.com/elastic/ecs-logging-go-zerolog/releases
    legacy_versions: []
  ecs_logging_java:
    current: '1.7.0' # https://github.com/elastic/ecs-logging-java/releases
    legacy_versions: [ '0.x' ]
  ecs_logging_nodejs:
    current: '1.5.3' # https://github.com/elastic/ecs-logging-nodejs/tags
    legacy_versions: []
  ecs_logging_php:
    current: '2.0.0' # https://github.com/elastic/ecs-logging-php/releases
    legacy_versions: []
  ecs_logging_python:
    current: '2.2.0' # https://github.com/elastic/ecs-logging-python/releases
    legacy_versions: []
  ecs_logging_ruby:
    current: '1.0.0' # https://github.com/elastic/ecs-logging-ruby/tags
    legacy_versions: []
  ecs:
    current: '9.0' #
    legacy_versions: [ '8.18', '8.17', '8.16', '8.15', '8.14', '8.13', '8.12', '8.11', '8.10', '8.9', '8.8', '8.7', '8.6', '8.5', '8.4', '8.3', '8.2', '8.1', '8.0', '1.12', '1.11', '1.10', '1.9', '1.8', '1.7', '1.6', '1.5', '1.4', '1.3', '1.2', '1.1', '1.0' ]
  elastic-stack-glossary:
    current: 'current'
    legacy_versions: []
  curator:
    current: 'current'
    legacy_versions: [ '7.0', '6.0', '5.8', '5.7', '5.6', '5.5', '5.4', '5.3', '5.2', '5.1', '5.0', '4.3', '4.2', '4.1', '4.0', '3.5', '3.4', '3.3' ]
  eland:
    current: '9.0.1' # https://github.com/elastic/eland/releases
    legacy_versions: []
  esf:
    current: '1.20.1' # https://github.com/elastic/elastic-serverless-forwarder/releases
    legacy_versions: []
  ingest-overview:
    current: 'current'
    legacy_versions: []
  integrations-developer:
    current: 'current'
    legacy_versions: []
  integrations:
    current: 'current'
    legacy_versions: []
  logstash-versioned-plugins:
    current: 'current'
    legacy_versions: []
  reference-architectures:
    current: 'current'
    legacy_versions: []
  search-ui:
    current: '1.24.0' # https://github.com/elastic/search-ui
    legacy_versions: []
  serverless:
    current: 'current'
    legacy_versions: []

```

</details>
