### ISSUE TITLE
Develop a central version config

### ISSUE THREAD

**Issue by bmorelli25** [elastic/docs-builder#1370]
## Summary

Establish a central location and single source of truth for tracking “base” and “current” versions for all versioned products. This will enable us to support dynamic content in status badges as described in #1369.

Base = The lowest supported version documented in the V3 site
Current = The latest released version

The “base” and “current” version for each repo will be assigned in [assembler.yml](https://github.com/elastic/docs-builder/blob/main/src/tooling/docs-assembler/assembler.yml). For every release, the docs release manager will be responsible for updating the “current” version in [assembler.yml](https://github.com/elastic/docs-builder/blob/main/src/tooling/docs-assembler/assembler.yml) for the versioning system being released. This would include not only Elastic Stack releases, but also other releases like Elastic Cloud Enterprise, APM agents, and more. For a full list of versioning systems, refer to [Versioning systems to be added to assembler.yml](https://docs.google.com/document/d/1P5g4YkCOMSynJspZeoIzib1fQfzgCRLcz-3rS6xKrck/edit?tab=t.0#heading=h.x98b437u4v9m).

## Example

```yaml
versions:
  stack: 		
    base:		9.0
    current:		9.1 # this is what the release manager would update
  cloud_enterprise: 	
    base:		4.0
    current:		4.1
  cloud_on_k8s: 	
    base: 		3.0
    current: 		3.2
  ...etc
```
