### ISSUE TITLE
Create Link Index

### ISSUE THREAD

**Issue by reakaleek** [elastic/docs-builder#164]
The Link Index is the s3 bucket that will hold the `links.json` artifacts from they individual docs builds.

**Comment by reakaleek** [comment]
# Link Index

The Link Index Service utilizes an AWS S3 bucket to store the `links.json` files
from each repository renamed to the repository name (e.g. `repository_name.json`).

## Authentication and Authorization to S3

It utilizes OIDC to allow GitHub Actions workflows to assume the
`elastic-docs-link-index-uploader-{{hash of repository name}}` role.

Each role is only allowed to write to the S3 bucket with the repository name as the key.

This way we can ensure that a repository can only write to its own `links.json` file.

To add or remove a repository from the Link Validation Service, you must update the
[allowed_repositories.yml](./allowed-repositories.yml) file.

## GitHub Actions Workflow Example

```yaml
on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Generate role ARN
        id: role_arn
        shell: python
        run: |
          import hashlib
          import os
          prefix = "elastic-docs-link-index-uploader-"
          aws_account_id = "197730964718"
          m = hashlib.sha256()
          m.update(os.environ["GITHUB_REPOSITORY"].encode('utf-8'))
          hash = m.hexdigest()[:64-len(prefix)]

          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            f.write(f"result=arn:aws:iam::{aws_account_id}:role/{prefix}{hash}")
      # authenticate to aws with oidc using the aws auth github action
      - name: authenticate to aws with oidc
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ steps.role_arn.outputs.result }}
          aws-region: us-east-1
      - name: upload the file to s3 to the root of the bucket
        run: |
          repository_name=$(echo ${{ github.repository }} | cut -d '/' -f 2)
          echo '{ "links": [] }' > links.json
          aws s3 cp "links.json" "s3://elastic-docs-link-index/${repository_name}.json"
```
