### ISSUE TITLE
`docset.yml` doesn't respect order of child folders

### ISSUE THREAD

**Issue by bmorelli25** [elastic/docs-builder#173]
### Bug

The order of child files is respected, but child folders are always moved to the bottom of the TOC after any standalone files.

### Expected

I expect the TOC order to match the `children` order in `docset.yml`.

### Example

In this file, the "Freeze" folder is the first item under the Migration TOC header.

```yaml
  - folder: migration
    children:
      - folder: freeze
        children:
          - file: index.md
          - file: codeowner.md
          - file: gh-action.md
      - file: index.md
      - file: guide.md
      - file: file-structure.md
      - file: mapping.md
      - file: tabs.md
```

However, when rendered, "Documentation Freeze" is the last item in the Migration TOC header:

<img width="272" alt="Image" src="https://github.com/user-attachments/assets/2fc9542f-589a-456e-9145-d6590c777286" />
