### ISSUE TITLE
Images with screenshot class

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/docs-builder#399]
In the old asciidoc system, images could optionally be marked as a `screenshot` through the `css` class `screenshot` to create a shadow around a mostly white image.

https://github.com/elastic/docs/blob/master/resources/web/style/img.pcss#L22-L24
```css
.screenshot img {
    box-shadow:  0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
  }
```

Is this functionality we want to port over to `docs-builder`?
