### ISSUE TITLE
[Feature Request]: Add ability to control the initial state of expanded/collapsed navigation items

### ISSUE THREAD

**Issue by reakaleek** [elastic/docs-builder#456]
### Prerequisites

- [x] I have searched existing issues to ensure this feature hasn't already been requested
- [x] I have tested using the latest version of docs-builder

### What problem are you trying to solve?

Currently, we can only set the level of the expanded state of the navigation.

E.g. we can say expand all level 1 nav items

### Proposed Solution

Add a new property called `expanded` into toc defintion, which is `false` by default.

E.g.

```yaml
toc:
  - file: index.md
  - hidden: developer-notes.md
  - folder: contribute
    expanded: true # <-- this is the new attribute
    children:
      - file: index.md
      - file: locally.md
      - file: on-the-web.md
      - file: move.md
  - folder: migration
```

This way we have more control which navigation items should be collapsed or expanded when the user visits the documentation site for the first time.

### How important is this feature to you?

Nice to have
