### ISSUE TITLE
Contents of code block are truncated when an annotation is used

### ISSUE THREAD

**Issue by shainaraskas** [elastic/docs-builder#577]
### Describe the bug

When I use the following code and annotate the `url` value with a `2`, the `url` value is truncated:

```yaml
xpack:
  security:
    authc:
      realms:
        active_directory:
          my_ad:
            order: 0
            domain_name: example.com <1>
            url: ldaps://dc1.ad.example.com:3269, ldaps://dc2.ad.example.com:3269 <2>
            load_balance:
              type: "round_robin" <3>
```

<img width="814" alt="Image" src="https://github.com/user-attachments/assets/37e35bac-3e51-4be3-be8e-e75fc602bff3" />

When I remove the annotation, the content is not truncated: 

```yaml
xpack:
  security:
    authc:
      realms:
        active_directory:
          my_ad:
            order: 0
            domain_name: example.com <1>
            url: ldaps://dc1.ad.example.com:3269, ldaps://dc2.ad.example.com:3269
            load_balance:
              type: "round_robin" <3>
```

<img width="798" alt="Image" src="https://github.com/user-attachments/assets/ae35bf8f-e592-4375-ba92-9b1446a12ba9" />

seems to be tied to the contents of this line specifically. if I put it in its own snippet, it fails in the same way

```yaml
url: ldaps://dc1.ad.example.com:3269, ldaps://dc2.ad.example.com:3269 <2>
```

<img width="805" alt="Image" src="https://github.com/user-attachments/assets/5d2d26d4-d116-4b5e-a600-9b98c019a286" />

and it doesn't have to be a `<2>`:

```yaml
url: ldaps://dc1.ad.example.com:3269, ldaps://dc2.ad.example.com:3269 <1>
```

<img width="807" alt="Image" src="https://github.com/user-attachments/assets/5165f6f0-d02b-4e86-bf6b-f62d200472dd" />

### Expected behavior

annotations do not impact code block contents (other than adding annotations)

### Steps to reproduce

see above

### Tooling

- [x] docs-builder
- [ ] migration tooling
- [ ] I'm not sure

**Comment by shainaraskas** [comment]
looks like it's related to slashes. seeing it here too: 

```yaml
xpack.security.authc.realms.oidc.oidc1: <1>
  order: 2 <2>
  rp.client_id: "the_client_id" <3>
  rp.response_type: code <4>
  rp.redirect_uri: "https://kibana.example.org:5601/api/security/oidc/callback" 
  op.issuer: "https://op.example.org" <6>
  op.authorization_endpoint: "https://op.example.org/oauth2/v1/authorize" <7>
  op.token_endpoint: "https://op.example.org/oauth2/v1/token" <8>
  op.jwkset_path: oidc/jwkset.json <9>
  op.userinfo_endpoint: "https://op.example.org/oauth2/v1/userinfo" <10>
  op.endsession_endpoint: "https://op.example.org/oauth2/v1/logout" <11>
  rp.post_logout_redirect_uri: "https://kibana.example.org:5601/security/logged_out" <12>
  claims.principal: sub <13>
  claims.groups: "http://example.info/claims/groups" <14>
```

<img width="800" alt="Image" src="https://github.com/user-attachments/assets/56e79ea8-40cb-4354-8d18-0a2bb3aa86e6" />
