### ISSUE TITLE
invalid `applies_to` keys can be set in front matter

### ISSUE THREAD

**Issue by shainaraskas** [elastic/docs-builder#610]
### Describe the bug

I passed the following key:

```
applies_to:
  deployment:
      serverless: all
      hosted: all
```

`hosted` and `serverless` is not a valid subkey of `deployment`, so the little tag didn't appear in my page. however, the PR passed CI with no problems

### Expected behavior

invalid keys throw CI errors

I realize that we want to allow custom keys, but in the other well-defined key/subkey areas we should do some validation

### Steps to reproduce

```
applies_to:
  deployment:
      serverless: all
      hosted: all
```

### Tooling

- [x] docs-builder
- [ ] migration tooling
- [ ] I'm not sure
