### ISSUE TITLE
Solo L1 sidebar entries act like they're parented to the previous L1

### ISSUE THREAD

**Issue by shainaraskas** [elastic/docs-builder#692]
### Describe the bug

Manage connectors and **Manage spaces** are L1s with no children. 

**Manage spaces** looks like it's part of **Users and Roles** ... and **Manage connectors** looks like it's part of the **Manage API keys** section ... due to the way solo L1s are styled

https://docs-v3-preview.elastic.dev/elastic/docs-content/tree/main/deploy-manage/manage-spaces

<img width="331" alt="Image" src="https://github.com/user-attachments/assets/0e1fc2d6-ef11-4f3e-a1c7-172ef9f64b97" />

toc.yml:
```
  - file: manage-spaces.md
  - file: api-keys.md
    children:
      - file: api-keys/elasticsearch-api-keys.md
      - file: api-keys/serverless-project-api-keys.md
      - file: api-keys/elastic-cloud-api-keys.md
      - file: api-keys/elastic-cloud-enterprise-api-keys.md
  - file: manage-connectors.md
 ```

### Expected behavior

the solo L1s are bolded and left-aligned like the L1s with children

### Tooling

- [ ] docs-builder
- [ ] migration tooling
- [ ] I'm not sure
