### ISSUE TITLE
[Feature Request]: CI checks to ensure unique URLs

### ISSUE THREAD

**Issue by lcawl** [elastic/docs-builder#771]
### Prerequisites

- [x] I have searched existing issues to ensure this feature hasn't already been requested
- [x] I have tested using the latest version of docs-builder

### What problem are you trying to solve?

Relates to https://github.com/elastic/docs-builder/issues/672, https://github.com/elastic/docs-builder/issues/672

It's not always completely obvious what the final URL for a page will be, so we ought to ensure that we have warnings or errors that prevent the creation of duplicate URLs. This will be particularly important if we have the ability to customize the URLs from a configuration file outside the repo where the source files exist (since it's even more removed from a contributor's awareness).

### Proposed Solution

Ensure there are PR checks that validate each page (using the full URL derived from `path_prefix` in `assembler.yml`.

### Examples and Research

If my preliminary understanding of the `assembler.yml` plans are correct and we could have something like this:

```yaml
- toc: docs-content://reference/elasticsearch
        children:
          - toc: elasticsearch://reference/elasticsearch
             path_prefix: reference/elasticsearch
      
          - toc: docs-content://reference/elasticsearch/clients
            path_prefix: reference/elasticsearch/clients
            children:
              - toc: go-elasticsearch://reference
                path_prefix: reference/elasticsearch/clients/go
```

Then it seems like someone could unwittingly create content in the `elasticsearch` or `docs-content` repos in a `docs/reference/elasticsearch/clients` folder, for example, that gets mixed up with (or worse silently overwrites) content from the `go-elasticsearch` (and other client) repos.

### How important is this feature to you?

Nice to have
